# Generated by Django 5.2.9 on 2026-02-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_systemstatusnews_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatusnews',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='When the infrastructure outage or reconfiguration starts (in your local timezone)', null=True, verbose_name='Start Date and Time'),
        ),
    ]
