# Generated by Django 5.2.9 on 2026-03-17 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_ciderfeatures_cidergroups_ciderinfrastructure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationnews',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationnews',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_integration_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrationnews',
            name='review_comments',
            field=models.TextField(blank=True, help_text='Comments from reviewer'),
        ),
        migrations.AddField(
            model_name='integrationnews',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationnews',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='User assigned to review this news', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_integration_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrationnews',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', help_text='Current workflow status', max_length=20),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_systemstatus_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='review_comments',
            field=models.TextField(blank=True, help_text='Comments from reviewer'),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='User assigned to review this news', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_systemstatus_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', help_text='Current workflow status', max_length=20),
        ),
        migrations.AlterField(
            model_name='integrationnews',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_integration_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemstatusnews',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_systemstatus_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
