# Generated by Django 5.2.9 on 2026-03-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_integrationnews_published_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationnews',
            options={'ordering': ['-created_at'], 'permissions': [('can_review_integrationnews', 'Can review Integration News'), ('can_publish_integrationnews', 'Can publish Integration News')], 'verbose_name': 'Integration News', 'verbose_name_plural': 'Integration News'},
        ),
        migrations.AlterModelOptions(
            name='systemstatusnews',
            options={'ordering': ['-start_datetime'], 'permissions': [('can_review_systemstatusnews', 'Can review System Status News'), ('can_publish_systemstatusnews', 'Can publish System Status News')], 'verbose_name': 'System and Infrastructure Status News', 'verbose_name_plural': 'System and Infrastructure Status News'},
        ),
    ]
