# Generated by Django 5.2.9 on 2026-03-25 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_focusareasection_owner_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focusareasection',
            options={'ordering': ['page_id', 'section_key'], 'permissions': [('can_review_focusareasection', 'Can review Focus Area Sections'), ('can_publish_focusareasection', 'Can publish Focus Area Sections')], 'verbose_name': 'Focus Area Section', 'verbose_name_plural': 'Focus Area Sections'},
        ),
        migrations.AddField(
            model_name='focusareasection',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focusareasection',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_focus_area_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='focusareasection',
            name='review_comments',
            field=models.TextField(blank=True, help_text='Comments from reviewer'),
        ),
        migrations.AddField(
            model_name='focusareasection',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focusareasection',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='User assigned to review this section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_focus_area_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='focusareasection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', help_text='Current workflow status', max_length=20),
        ),
    ]
