# Generated by Django 5.2.14 on 2026-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_news', '0004_alter_systemstatusnews_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstatusnews',
            name='drupal_nid',
            field=models.CharField(blank=True, db_index=True, help_text='Original Drupal node ID, for items imported from the legacy portal', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='drupal_vid',
            field=models.CharField(blank=True, help_text='Original Drupal revision ID, for items imported from the legacy portal', max_length=32, null=True),
        ),
    ]
