# Generated by Django 5.2.14 on 2026-09-08 16:51

import djangocms_text_ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_news', '0005_systemstatusnews_outage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatusnews',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='News Content'),
        ),
    ]
