# Generated by Django 5.2.14 on 2026-09-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_news', '0006_alter_systemstatusnews_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemstatusnews',
            options={'ordering': ['-start_datetime'], 'permissions': [('can_publish_systemstatusnews', 'Can publish System Status News')], 'verbose_name': 'System and Infrastructure Status News', 'verbose_name_plural': 'System and Infrastructure Status News'},
        ),
        migrations.AlterField(
            model_name='systemstatusnews',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', help_text='Current workflow status', max_length=20),
        ),
    ]
