# Generated by Django 5.2.9 on 2026-02-06 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_portalcms_django', '0006_alter_systemstatusnews_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemstatusnews',
            options={'ordering': ['-start_datetime'], 'verbose_name': 'System and Infrastructure Status News', 'verbose_name_plural': 'System and Infrastructure Status News'},
        ),
        migrations.RemoveField(
            model_name='systemstatusnews',
            name='title',
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='affected_infrastructure',
            field=models.CharField(blank=True, help_text='Resource ID(s) from CIDER (comma-separated if multiple)', max_length=255, verbose_name='Affected Infrastructure'),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='email_list',
            field=models.CharField(blank=True, help_text='Comma-separated email addresses', max_length=500, verbose_name='Email Recipients'),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='When this outage or configuration change ends. May be left blank for permanent configuration changes.', null=True, verbose_name='End Date and Time'),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='infrastructure_news_type',
            field=models.CharField(choices=[('degraded', 'Degraded'), ('introduction', 'Introduction'), ('outage_full', 'Outage Full'), ('outage_partial', 'Outage Partial'), ('reconfiguration', 'Reconfiguration'), ('retirement', 'Retirement')], default='outage_full', max_length=50, verbose_name='Infrastructure News Type'),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='post_to_slack',
            field=models.BooleanField(default=False, verbose_name='Post to Slack'),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Send Email Notification'),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='slack_channel',
            field=models.CharField(blank=True, help_text='e.g., #operations-alerts', max_length=100, verbose_name='Slack Channel'),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the infrastructure outage or reconfiguration starts (in your local timezone)', verbose_name='Start Date and Time'),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='subject',
            field=models.CharField(default='Untitled', max_length=200, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='systemstatusnews',
            name='content',
            field=models.TextField(verbose_name='News Content'),
        ),
    ]
