# Generated by Django 5.2.9 on 2026-03-20 15:10

from django.db import migrations, models


INTEGRATION_ELEMENTS = [
    ('cloud_roadmap', 'ACCESS Allocated Production Cloud - Integration Roadmap'),
    ('compute_roadmap', 'ACCESS Allocated Production Compute - Integration Roadmap'),
    ('storage_roadmap', 'ACCESS Allocated Production Storage - Integration Roadmap'),
    ('science_gateway_roadmap', 'ACCESS Integrated Science Gateway - Integration Roadmap'),
    ('nagios', 'ACCESS Monitoring Service - Nagios'),
    ('online_service_roadmap', 'ACCESS Production Online Service - Integration Roadmap'),
    ('aws_registry', 'ACCESS Public AWS Container Registry'),
    ('cider', 'CiDeR - CyberInfrastructure Description Repository'),
    ('ipf', 'Information Publishing Framework (IPF) tool for publishing compute resource information'),
]


def seed_and_backfill(apps, schema_editor):
    IntegrationElement = apps.get_model('operations_portalcms_django', 'IntegrationElement')
    IntegrationNews = apps.get_model('operations_portalcms_django', 'IntegrationNews')
    SystemStatusNews = apps.get_model('operations_portalcms_django', 'SystemStatusNews')
    CiderInfrastructure = apps.get_model('operations_portalcms_django', 'CiderInfrastructure')

    for code, label in INTEGRATION_ELEMENTS:
        IntegrationElement.objects.update_or_create(code=code, defaults={'label': label})

    integration_elements = {
        element.code: element
        for element in IntegrationElement.objects.all()
    }
    infrastructures = {
        infra.info_resourceid: infra
        for infra in CiderInfrastructure.objects.all()
    }

    for news in IntegrationNews.objects.all():
        if news.affected_element and news.affected_element in integration_elements:
            news.affected_elements.add(integration_elements[news.affected_element])

    for news in SystemStatusNews.objects.all():
        if not news.affected_infrastructure:
            continue
        values = [value.strip() for value in news.affected_infrastructure.split(',') if value.strip()]
        matched = [infrastructures[value] for value in values if value in infrastructures]
        if matched:
            news.affected_infrastructure_items.add(*matched)


class Migration(migrations.Migration):

    dependencies = [
        ('operations_portalcms_django', '0011_alter_integrationnews_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationElement',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Integration Element',
                'verbose_name_plural': 'Integration Elements',
                'db_table': 'operations_portalcms_django_integrationelement',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='integrationnews',
            name='affected_elements',
            field=models.ManyToManyField(blank=True, related_name='integration_news_items', to='operations_portalcms_django.integrationelement', verbose_name='Affected Elements'),
        ),
        migrations.AddField(
            model_name='systemstatusnews',
            name='affected_infrastructure_items',
            field=models.ManyToManyField(blank=True, related_name='system_status_news_items', to='operations_portalcms_django.ciderinfrastructure', verbose_name='Affected Infrastructure Items'),
        ),
        migrations.RunPython(seed_and_backfill, migrations.RunPython.noop),
    ]
