# Generated by Django 5.2.9 on 2026-03-23 17:57

import django.db.models.deletion
import djangocms_text_ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('operations_portalcms_django', '0012_integrationelement_and_multi_value_news_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusAreaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('section_1', 'Section 1'), ('section_2', 'Section 2'), ('section_3', 'Section 3'), ('section_4', 'Section 4'), ('section_5', 'Section 5'), ('additional_links', 'Additional Links')], max_length=32)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('body', djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='focus_area_sections', to='auth.group')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_area_sections', to='cms.page')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_focus_area_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Focus Area Section',
                'verbose_name_plural': 'Focus Area Sections',
                'db_table': 'operations_portalcms_django_focusareasection',
                'ordering': ['page_id', 'section_key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'section_key'), name='focus_area_section_page_key_unique')],
            },
        ),
    ]
