# Generated by Django 5.2.9 on 2026-03-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations_portalcms_django', '0015_alter_focusareasection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focusareasection',
            options={'ordering': ['page_id', 'section_key'], 'verbose_name': 'Focus Area Section', 'verbose_name_plural': 'Focus Area Sections'},
        ),
        migrations.RemoveField(
            model_name='focusareasection',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='focusareasection',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='focusareasection',
            name='review_comments',
        ),
        migrations.RemoveField(
            model_name='focusareasection',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='focusareasection',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='focusareasection',
            name='status',
        ),
    ]
