# Generated by Codex on 2026-04-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations_portalcms_django", "0016_alter_focusareasection_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FocusAreaSection",
        ),
    ]
