"""
Django settings for Operations Portal CMS project.

Generated by 'django-admin startproject' using Django 5.2.9.
Enhanced framework drafted by Claude Sonnet 4.5 (January 28, 2026)

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import json
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

##### ACCESS-CI CUSTOMIZATIONS #####
# `APP_CONFIG` is the single supported runtime config entry point for this app.
# For local repo workflows, `portal.conf.dev.json` is the canonical sample file.
if 'APP_CONFIG' not in os.environ:
    print('Missing APP_CONFIG environment variable')
    sys.exit(1)

config_file = Path(os.environ['APP_CONFIG'])

try:
    with open(config_file, 'r', encoding='utf-8') as f:
        CONF = json.load(f)
except (ValueError, OSError):
    print(f'Failed to load APP_CONFIG={config_file}')
    raise

# Keep the required-key contract explicit so sample configs and deployment
# automation can stay aligned as the runtime moves toward infra management.
required_config_keys = [
    'DJANGO_SECRET_KEY',
]
missing_required_keys = [key for key in required_config_keys if key not in CONF or CONF[key] in ('', None)]
if missing_required_keys:
    print(f'Missing required APP_CONFIG keys: {", ".join(missing_required_keys)}')
    sys.exit(1)

# Inject config values into the environment for settings that still use os.environ.
for key, value in CONF.items():
    if key not in os.environ:
        if isinstance(value, list):
            os.environ[key] = ','.join(str(v) for v in value)
        elif isinstance(value, bool):
            os.environ[key] = 'True' if value else 'False'
        elif value is None:
            os.environ[key] = ''
        else:
            os.environ[key] = str(value)

if CONF.get('API_KEY'):
    os.environ['API_KEY'] = str(CONF['API_KEY'])


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = CONF['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',') if os.environ.get('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'cms',
    'djangocms_versioning',
    'menus',
    'treebeard',
    'sekizai',
    'django_bootstrap5',
    'operations_portalcms_django.apps.OperationsPortalcmsDjangoConfig',
    # Django CMS plugins
    'djangocms_text_ckeditor',
    'djangocms_picture',
    'djangocms_file',
    'djangocms_link',
    'djangocms_video',
    # Django Filer
    'filer',
    'easy_thumbnails',
    # socialaccount info
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.cilogon',
    # access_django_users app
    'access_django_user_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'operations_portalcms_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'operations_portalcms_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_SEARCH_PATH = os.environ.get('DB_SEARCH_PATH', '"$user",public')
DB_SSLMODE = os.environ.get('DB_SSLMODE', '')
DB_SSLROOTCERT = os.environ.get('DB_SSLROOTCERT', '')
DB_SSLCERT = os.environ.get('DB_SSLCERT', '')
DB_SSLKEY = os.environ.get('DB_SSLKEY', '')

DB_OPTIONS = {
    # Keep schema resolution explicit during the role/schema cutover.
    'options': f'-c search_path={DB_SEARCH_PATH}',
}

if DB_SSLMODE:
    DB_OPTIONS['sslmode'] = DB_SSLMODE
if DB_SSLROOTCERT:
    DB_OPTIONS['sslrootcert'] = DB_SSLROOTCERT
if DB_SSLCERT:
    DB_OPTIONS['sslcert'] = DB_SSLCERT
if DB_SSLKEY:
    DB_OPTIONS['sslkey'] = DB_SSLKEY

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_DATABASE', 'portalcms1'),
        'USER': os.environ.get('DJANGO_USER', 'portal_django'),
        'PASSWORD': os.environ.get('DJANGO_PASS', ''),
        'HOST': os.environ.get('DB_HOSTNAME_WRITE', os.environ.get('DB_HOSTNAME_READ', 'localhost')),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': DB_OPTIONS,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SITE_ID = 1

# Django CMS Settings
CMS_CONFIRM_VERSION4 = True

# Hide CMS Toolbar completely - require admin interface for page management
CMS_TOOLBAR_HIDE = False  # Temporarily enable for page creation
CMS_TOOLBAR_ANONYMOUS_ON = False  # Hide toolbar for anonymous users

# CMS Language Settings
CMS_LANGUAGES = {
    1: [
        {
            'code': 'en',
            'name': 'English',
            'public': True,
            'hide_untranslated': False,
            'redirect_on_fallback': True,
        },
    ],
    'default': {
        'public': True,
        'hide_untranslated': False,
        'redirect_on_fallback': True,
    }
}

CMS_TEMPLATES = [
    ('page.html', 'Page'),
    ('feature.html', 'Page with Feature'),
    ('infrastructure.html', 'Infrastructure Integration'),
    ('focus_area.html', 'Focus Area Page'),
]
CMS_PERMISSION = True
CMS_PUBLIC_FOR = 'all'
CMS_PLACEHOLDER_CONF = {}
DJANGOCMS_VERSIONING_LOCK_VERSIONS = True
DJANGOCMS_VERSIONING_ON_PUBLISH_REDIRECT = 'published'
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Thumbnail Settings
THUMBNAIL_HIGH_RESOLUTION = True
THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)
THUMBNAIL_PRESERVE_EXTENSIONS = True
THUMBNAIL_ALIASES = {
    '': {
        'default': {'size': (300, 300), 'crop': True},
        'large': {'size': (800, 600), 'crop': False},
    },
}

# Text Editor Settings
TEXT_SAVE_IMAGE_FUNCTION = 'djangocms_text_ckeditor.picture_save.create_picture_plugin'
TEXT_ADDITIONAL_TAGS = ('iframe',)
TEXT_ADDITIONAL_ATTRIBUTES = ('scrolling', 'allowfullscreen', 'frameborder')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', str(BASE_DIR / 'staticfiles'))
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Admin Interface Settings
# Force dark mode in Django admin
import os
if 'DJANGO_COLORS' not in os.environ:
    os.environ['DJANGO_COLORS'] = 'dark'

# Application Logging
APP_LOG = os.environ.get('APP_LOG', str(BASE_DIR / 'var' / 'portalcms.log'))
APP_VERSION = os.environ.get('APP_VERSION', 'dev')
SYSLOG_SOCK = os.environ.get('SYSLOG_SOCK', '/var/run/syslog')

# API Configuration
API_BASE = os.environ.get('API_BASE', '')

# ==================== ALLAUTH SOCIALACCOUNT CONFIGURATION ====================
# CILogon OAuth2 Configuration - matches Service Index functionality

SOCIALACCOUNT_PROVIDERS = {
    'cilogon': {
        'SCOPE': [
            'openid',
            'profile',
            'email',
            'org.cilogon.userinfo',
        ],
        'VERIFIED_EMAIL': True,
        'VERSION': 'v1',
        'FIELDS_MAPPING': {
            'email': 'email',
            'name': 'name',
            'first_name': 'given_name',
            'last_name': 'family_name',
            'picture': 'picture',
            'eppn': 'eppn',
        },
        'APP': {
            'client_id': os.environ.get('CILOGON_CLIENT_ID', ''),
            'secret': os.environ.get('CILOGON_CLIENT_SECRET', ''),
            'key': '',
        },
    },
}

AUTHENTICATION_BACKENDS = [
    # Allauth authentication backend (required for socialaccount)
    'allauth.account.auth_backends.AuthenticationBackend',
    
    # Django's default auth backend (for superuser/staff users)
    'django.contrib.auth.backends.ModelBackend',
]

# Allauth Account Settings
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_PROFILE_FIELDS = ['email', 'first_name', 'last_name']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CMS related settings
CMS_PAGE_WIZARD_CONTENT_PLACEHOLDER = "content"
CMS_PAGE_WIZARD_CONTENT_PLUGIN = "TextPlugin"

# Logging setup
import logging
from logging.handlers import SysLogHandler

if DEBUG or not os.path.exists('/dev/log'):
    DEFAULT_LOG = 'console'
else:
    DEFAULT_LOG = 'syslog'

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'simple': {
#             'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s'
#         }
#     },
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': CONF['APP_LOG'],
#             'formatter': 'simple'
#         }
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'WARNING'
#         },
#         'django.server': {
#             'handlers': ['file'],
# #            'propagate': True,
#             'level': 'DEBUG'
#         },
#         'services': {
#             'handlers': ['file'],
#             'level': 'DEBUG'
#         }
#     }
# }

APP_NAME = 'Portal CMS'
# APP_VERSION = CONF['APP_VERSION']
