# Generated by Django 5.2.14 on 2026-06-18 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('integration_news', '0003_rename_plugin_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationnews',
            name='review_comments',
            field=models.TextField(blank=True, help_text='Comments from reviewer'),
        ),
        migrations.AlterField(
            model_name='integrationnews',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='User assigned to review this news', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_integration_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integrationnews',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', help_text='Current workflow status', max_length=20),
        ),
        migrations.AlterField(
            model_name='integrationnewsitemplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
    ]
