# Generated by Django 5.2.14 on 2026-09-08 16:51

import djangocms_text_ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration_news', '0005_integrationnews_integration_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationnews',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(),
        ),
    ]
