# Generated by Django 5.2.14 on 2026-09-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_news', '0006_alter_integrationnews_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationnews',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish_integrationnews', 'Can publish Integration News')], 'verbose_name': 'Integration News', 'verbose_name_plural': 'Integration News'},
        ),
        migrations.AlterField(
            model_name='integrationnews',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', help_text='Current workflow status', max_length=20),
        ),
    ]
